name: good-first-issue
region: fra
static_sites:
  - dockerfile_path: Dockerfile
    github:
      branch: deploy-to-platform
      deploy_on_push: true
      repo: ocean/good-first-issue
    name: good-first-issue
    output_dir: /public
